Vagrant.configure("2") do |config|
 
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end
  config.vm.define :servidor do |servidor|
    config.vm.box = "bento/centos-stream-9"
    config.vm.box_version = "202301.20.0"
    servidor.vm.provision "shell", path: "servidor.sh.txt"
    servidor.vm.network :private_network, ip: "192.168.50.4"
    servidor.vm.hostname = "servidor"
    servidor.vm.provider "virtualbox" do |v|
      v.cpus = 2  
    end
  end
 
end

